/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.acrs.juscadastro.view.panel;

import com.acrs.juscadastro.control.ContatoControl;
import com.acrs.juscadastro.util.MaxLengthTextDocument;
import com.acrs.juscadastro.util.ValidaDataString;
import com.acrs.juscadastro.view.interfaces.IPnlPessoal;
import javax.swing.JFormattedTextField;
import javax.swing.JTextField;

/**
 *
 * @author acrs
 */
public class PnlBalanco extends javax.swing.JPanel /* implements IPnlPessoal */{

    /**
     * Creates new form PContato
     */
    public PnlBalanco() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome = new javax.swing.JLabel();
        txtCPFJ = new javax.swing.JTextField();
        lblNascimento = new javax.swing.JLabel();
        lblCargo = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        lblNascimento1 = new javax.swing.JLabel();
        txtCPFJ1 = new javax.swing.JTextField();
        lblCargo1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Lançamento de Balanço"));

        lblNome.setDisplayedMnemonic('m');
        lblNome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNome.setText("Data:");

        txtCPFJ.setDocument(new MaxLengthTextDocument(14));
        txtCPFJ.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCPFJ.setText("10047953780");
        txtCPFJ.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCPFJFocusGained(evt);
            }
        });

        lblNascimento.setDisplayedMnemonic('a');
        lblNascimento.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNascimento.setText("Crédito:");

        lblCargo.setDisplayedMnemonic('r');
        lblCargo.setText("Saldo:");

        lblNascimento1.setDisplayedMnemonic('a');
        lblNascimento1.setText("Crédito:");

        txtCPFJ1.setDocument(new MaxLengthTextDocument(14));
        txtCPFJ1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCPFJ1.setText("10047953780");
        txtCPFJ1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCPFJ1FocusGained(evt);
            }
        });

        lblCargo1.setDisplayedMnemonic('r');
        lblCargo1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCargo1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCargo1.setText("R$ 0,00");

        jButton1.setText("Atualizar Saldo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNascimento, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                    .addComponent(lblNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(txtCPFJ))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNascimento1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCPFJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCargo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCargo1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNome)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNascimento)
                    .addComponent(txtCPFJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNascimento1)
                    .addComponent(txtCPFJ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCargo)
                    .addComponent(lblCargo1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCPFJFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCPFJFocusGained
        txtCPFJ.selectAll();
    }//GEN-LAST:event_txtCPFJFocusGained

    private void txtCPFJ1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCPFJ1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPFJ1FocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblCargo1;
    private javax.swing.JLabel lblNascimento;
    private javax.swing.JLabel lblNascimento1;
    private javax.swing.JLabel lblNome;
    private javax.swing.JTextField txtCPFJ;
    private javax.swing.JTextField txtCPFJ1;
    // End of variables declaration//GEN-END:variables

    private Integer idAgendaTelefonica;

    public void limpar() {
        idAgendaTelefonica = null;
//        txfNascimento.setText("");
        txtCPFJ.setText("");
 //       txtCargo.setText("");
 //       txtEmpresa.setText("");
//        txtNome.setText("");
    }

    public void habilitar() {
        editar(true);
    }
    
    public void desabilitar() {
        editar(false);
    }
            
    private void editar(boolean op) {
//        txfNascimento.setEditable(op);
        txtCPFJ.setEditable(op);
//        txtCargo.setEditable(op);
//        txtEmpresa.setEditable(op);
//        txtNome.setEditable(op);
    }
    
    public String validarPreenchimentoCPFJ() {
        if (txtCPFJ.getText().trim().equals("")) {
            txtCPFJ.requestFocus();
            java.awt.Toolkit.getDefaultToolkit().beep();
            return "Por favor, preencher o CPF/CNPJ.";            
        }        
        return "";
    }
    
    public String validarUnicidadeCPFJ() {
        String cpfj = txtCPFJ.getText().trim();
        if (ContatoControl.cpfjExiste(cpfj) && idAgendaTelefonica == null) {
            txtCPFJ.requestFocus();
            java.awt.Toolkit.getDefaultToolkit().beep();
            return "CPF/CNPJ já está cadastrado.";
        }
        return "";
    }
    
/*    public String validarPreenchimentoNome() {
        if (txtNome.getText().trim().equals("")) {
            txtNome.requestFocus();
            java.awt.Toolkit.getDefaultToolkit().beep();
            return "Por favor, preencher o nome.";
        }        
        return "";
    }*/
    
    public String validarUnicidadeNome() {
/*        String nome = txtNome.getText().trim();
        if (AgendaTelefonicaControl.nomeExiste(nome) && idAgendaTelefonica == null) {
            txtNome.requestFocus();
            java.awt.Toolkit.getDefaultToolkit().beep();
            return "Nome já está cadastrado.";
        }*/
        return "";
    }
    
    public String validarFormatoNascimento() {
  /*      String nascimento = txfNascimento.getText();
        if (!nascimento.equals("  /  /    ")) {
            if (!ValidaDataString.validar("dd/MM/yyyy", nascimento)) {
                txfNascimento.setText("");
                txfNascimento.requestFocus();
                java.awt.Toolkit.getDefaultToolkit().beep();
                return "Data [" + nascimento + "] não está válida.";
            }
        }*/
        return "";
    }
    
 /*   public JFormattedTextField getTxfNascimento() {
        return txfNascimento;
    }*/

    public JTextField getTxtCPFJ() {
        return txtCPFJ;
    }

   /* public JTextField getTxtCargo() {
        return txtCargo;
    }*/

  /*  public JTextField getTxtEmpresa() {
        return txtEmpresa;
    }*/

    /*public JTextField getTxtNome() {
        return txtNome;
    }*/

    public Integer getIdAgendaTelefonica() {
        return idAgendaTelefonica;
    }

    public void setIdAgendaTelefonica(Integer idAgendaTelefonica) {
        this.idAgendaTelefonica = idAgendaTelefonica;
    }
        
}
