/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.acrs.juscadastro.view.panel;

import com.acrs.juscadastro.util.MaxLengthTextDocument;
import com.acrs.juscadastro.view.interfaces.IPnlContactar;
import javax.swing.JTextField;

/**
 *
 * @author acrs
 */
public class PnlContactar extends javax.swing.JPanel implements IPnlContactar {

    /**
     * Creates new form PContato
     */
    public PnlContactar() {
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTelFixo = new javax.swing.JLabel();
        txtTelFixo_DDD = new javax.swing.JTextField();
        lblTelMovel = new javax.swing.JLabel();
        txtTelFixo_Numero = new javax.swing.JTextField();
        lblTelFax = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtTelMovel_DDD = new javax.swing.JTextField();
        txtTelMovel_Numero = new javax.swing.JTextField();
        txtTelFax_DDD = new javax.swing.JTextField();
        txtTelFax_Numero = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Contato"));

        lblTelFixo.setDisplayedMnemonic('.');
        lblTelFixo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTelFixo.setLabelFor(txtTelFixo_DDD);
        lblTelFixo.setText("Tel. Fixo:");

        txtTelFixo_DDD.setDocument(new MaxLengthTextDocument(2));
        txtTelFixo_DDD.setText("21");
        txtTelFixo_DDD.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTelFixo_DDDFocusGained(evt);
            }
        });

        lblTelMovel.setDisplayedMnemonic('v');
        lblTelMovel.setLabelFor(txtTelMovel_DDD);
        lblTelMovel.setText("Tel. Móvel:");

        txtTelFixo_Numero.setDocument(new MaxLengthTextDocument(9));
        txtTelFixo_Numero.setText("35465478");
        txtTelFixo_Numero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTelFixo_NumeroFocusGained(evt);
            }
        });

        lblTelFax.setDisplayedMnemonic('x');
        lblTelFax.setLabelFor(txtTelFax_DDD);
        lblTelFax.setText("Tel. Fax:");

        txtEmail.setDocument(new MaxLengthTextDocument(200));
        txtEmail.setText("allan.carloss@gmail.com");
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
        });

        txtTelMovel_DDD.setDocument(new MaxLengthTextDocument(2));
        txtTelMovel_DDD.setText("21");
        txtTelMovel_DDD.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTelMovel_DDDFocusGained(evt);
            }
        });

        txtTelMovel_Numero.setDocument(new MaxLengthTextDocument(9));
        txtTelMovel_Numero.setText("969712222");
        txtTelMovel_Numero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTelMovel_NumeroFocusGained(evt);
            }
        });

        txtTelFax_DDD.setDocument(new MaxLengthTextDocument(2));
        txtTelFax_DDD.setText("21");
        txtTelFax_DDD.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTelFax_DDDFocusGained(evt);
            }
        });

        txtTelFax_Numero.setDocument(new MaxLengthTextDocument(9));
        txtTelFax_Numero.setText("24935232");
        txtTelFax_Numero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTelFax_NumeroFocusGained(evt);
            }
        });

        lblEmail.setDisplayedMnemonic('l');
        lblEmail.setLabelFor(txtEmail);
        lblEmail.setText("E-mail:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTelFixo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTelFixo_DDD, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTelFixo_Numero, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTelMovel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTelMovel_DDD, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTelMovel_Numero, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTelFax)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTelFax_DDD, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTelFax_Numero, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelFixo)
                    .addComponent(txtTelFixo_DDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelMovel)
                    .addComponent(txtTelFixo_Numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelFax)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelMovel_DDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelMovel_Numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelFax_DDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelFax_Numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTelFixo_DDDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelFixo_DDDFocusGained
        txtTelFixo_DDD.selectAll();
    }//GEN-LAST:event_txtTelFixo_DDDFocusGained

    private void txtTelFixo_NumeroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelFixo_NumeroFocusGained
        txtTelFixo_Numero.selectAll();
    }//GEN-LAST:event_txtTelFixo_NumeroFocusGained

    private void txtTelMovel_DDDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelMovel_DDDFocusGained
        txtTelMovel_DDD.selectAll();
    }//GEN-LAST:event_txtTelMovel_DDDFocusGained

    private void txtTelMovel_NumeroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelMovel_NumeroFocusGained
        txtTelMovel_Numero.selectAll();
    }//GEN-LAST:event_txtTelMovel_NumeroFocusGained

    private void txtTelFax_DDDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelFax_DDDFocusGained
        txtTelFax_DDD.selectAll();
    }//GEN-LAST:event_txtTelFax_DDDFocusGained

    private void txtTelFax_NumeroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelFax_NumeroFocusGained
        txtTelFax_Numero.selectAll();
    }//GEN-LAST:event_txtTelFax_NumeroFocusGained

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
        txtEmail.selectAll();
    }//GEN-LAST:event_txtEmailFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblTelFax;
    private javax.swing.JLabel lblTelFixo;
    private javax.swing.JLabel lblTelMovel;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtTelFax_DDD;
    private javax.swing.JTextField txtTelFax_Numero;
    private javax.swing.JTextField txtTelFixo_DDD;
    private javax.swing.JTextField txtTelFixo_Numero;
    private javax.swing.JTextField txtTelMovel_DDD;
    private javax.swing.JTextField txtTelMovel_Numero;
    // End of variables declaration//GEN-END:variables
    
    public void limpar() {
        txtEmail.setText("");
        txtTelFax_DDD.setText("");
        txtTelFax_Numero.setText("");
        txtTelFixo_DDD.setText("");
        txtTelFixo_Numero.setText("");
        txtTelMovel_DDD.setText("");
        txtTelMovel_Numero.setText("");
    }
    
    public void habilitar() {
        editar(true);
    }
    
    public void desabilitar() {
        editar(false);
    }
            
    private void editar(boolean op) {
        txtEmail.setEditable(op);
        txtTelFax_DDD.setEditable(op);
        txtTelFax_Numero.setEditable(op);
        txtTelFixo_DDD.setEditable(op);
        txtTelFixo_Numero.setEditable(op);
        txtTelMovel_DDD.setEditable(op);
        txtTelMovel_Numero.setEditable(op);
    }

    public JTextField getTxtEmail() {
        return txtEmail;
    }

    public JTextField getTxtTelFax_DDD() {
        return txtTelFax_DDD;
    }

    public JTextField getTxtTelFax_Numero() {
        return txtTelFax_Numero;
    }

    public JTextField getTxtTelFixo_DDD() {
        return txtTelFixo_DDD;
    }

    public JTextField getTxtTelFixo_Numero() {
        return txtTelFixo_Numero;
    }

    public JTextField getTxtTelMovel_DDD() {
        return txtTelMovel_DDD;
    }

    public JTextField getTxtTelMovel_Numero() {
        return txtTelMovel_Numero;
    }
   
}
