/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.acrs.juscadastro.view.dialog;

import com.acrs.juscadastro.control.ContatoControl;
import com.toedter.calendar.JDateChooser;
import java.awt.event.KeyEvent;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author acrs
 */
public class DlgAgendaTelefonicaLocalizar extends javax.swing.JDialog {

    /**
     * Creates new form DlgAgendaLocalizar
     *
     * @param parent
     * @param modal
     */
    public DlgAgendaTelefonicaLocalizar(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        agruparOpcoes();
        dtcLocalizar.setVisible(false);
        mostrarFiltroAtual();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgpLocalizar = new javax.swing.ButtonGroup();
        pnlLocalizarPor = new javax.swing.JPanel();
        rbtTodos = new javax.swing.JRadioButton();
        rbtNome = new javax.swing.JRadioButton();
        rbtEmpresa = new javax.swing.JRadioButton();
        rbtNascimento = new javax.swing.JRadioButton();
        rbtNotas = new javax.swing.JRadioButton();
        lblLocalizar = new javax.swing.JLabel();
        pnlValor = new javax.swing.JPanel();
        txtLocalizar = new javax.swing.JTextField();
        btnOk = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        dtcLocalizar = new com.toedter.calendar.JDateChooser();
        lblMensagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Localizar Agenda Telefônica");
        setIconImage(new ImageIcon(getClass().getResource("/com/acrs/juscadastro/view/img/contatos_32x32.png")).getImage());
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlLocalizarPor.setBorder(javax.swing.BorderFactory.createTitledBorder("Localizar por:"));

        rbtTodos.setSelected(true);
        rbtTodos.setText("Todos");
        rbtTodos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbtTodosItemStateChanged(evt);
            }
        });

        rbtNome.setText("Nome");
        rbtNome.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbtNomeItemStateChanged(evt);
            }
        });

        rbtEmpresa.setText("Empresa");
        rbtEmpresa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbtEmpresaItemStateChanged(evt);
            }
        });

        rbtNascimento.setText("Nascimento");
        rbtNascimento.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbtNascimentoItemStateChanged(evt);
            }
        });

        rbtNotas.setText("Notas");
        rbtNotas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbtNotasItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout pnlLocalizarPorLayout = new javax.swing.GroupLayout(pnlLocalizarPor);
        pnlLocalizarPor.setLayout(pnlLocalizarPorLayout);
        pnlLocalizarPorLayout.setHorizontalGroup(
            pnlLocalizarPorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLocalizarPorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLocalizarPorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtTodos)
                    .addComponent(rbtNome)
                    .addComponent(rbtEmpresa)
                    .addComponent(rbtNascimento)
                    .addComponent(rbtNotas))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlLocalizarPorLayout.setVerticalGroup(
            pnlLocalizarPorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLocalizarPorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtTodos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtEmpresa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtNascimento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbtNotas))
        );

        getContentPane().add(pnlLocalizarPor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        lblLocalizar.setText("Texto a localizar:");
        getContentPane().add(lblLocalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 11, -1, -1));

        pnlValor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtLocalizar.setEditable(false);
        txtLocalizar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLocalizarKeyReleased(evt);
            }
        });
        pnlValor.add(txtLocalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, -1));

        btnOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/acrs/juscadastro/view/img/ok_32x32.png"))); // NOI18N
        btnOk.setMnemonic('k');
        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });
        pnlValor.add(btnOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 110, -1));

        btnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/acrs/juscadastro/view/img/fechar_32x32.png"))); // NOI18N
        btnFechar.setMnemonic('f');
        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });
        pnlValor.add(btnFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 110, -1));
        pnlValor.add(dtcLocalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, -1));

        lblMensagem.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblMensagem.setForeground(new java.awt.Color(255, 0, 0));
        pnlValor.add(lblMensagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 230, 20));

        getContentPane().add(pnlValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 30, 240, 140));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        if (!rbtTodos.isSelected() && txtLocalizar.isVisible() && txtLocalizar.getText().trim().length() == 0) {
            lblMensagem.setText("Digite um texto.");
            txtLocalizar.requestFocus();
            return;
        }
        if (dtcLocalizar.isVisible() && dtcLocalizar.getCalendar() == null) {
            lblMensagem.setText("Selecione uma data.");
            dtcLocalizar.requestFocus();
            return;
        }
        lblMensagem.setText("");
        try {
            ContatoControl.localizarRegistros(this);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
        this.dispose();
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void rbtTodosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbtTodosItemStateChanged
        selecionarTipoBusca();
    }//GEN-LAST:event_rbtTodosItemStateChanged

    private void rbtNomeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbtNomeItemStateChanged
        selecionarTipoBusca();
    }//GEN-LAST:event_rbtNomeItemStateChanged

    private void rbtEmpresaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbtEmpresaItemStateChanged
        selecionarTipoBusca();
    }//GEN-LAST:event_rbtEmpresaItemStateChanged

    private void rbtNascimentoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbtNascimentoItemStateChanged
        selecionarTipoBusca();
    }//GEN-LAST:event_rbtNascimentoItemStateChanged

    private void rbtNotasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbtNotasItemStateChanged
        selecionarTipoBusca();
    }//GEN-LAST:event_rbtNotasItemStateChanged

    private void txtLocalizarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLocalizarKeyReleased
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {
            btnOk.doClick();
        }
    }//GEN-LAST:event_txtLocalizarKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (UnsupportedLookAndFeelException | ClassNotFoundException | InstantiationException | IllegalAccessException e) {
        }

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgAgendaTelefonicaLocalizar dialog = new DlgAgendaTelefonicaLocalizar(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgpLocalizar;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnOk;
    private com.toedter.calendar.JDateChooser dtcLocalizar;
    private javax.swing.JLabel lblLocalizar;
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JPanel pnlLocalizarPor;
    private javax.swing.JPanel pnlValor;
    private javax.swing.JRadioButton rbtEmpresa;
    private javax.swing.JRadioButton rbtNascimento;
    private javax.swing.JRadioButton rbtNome;
    private javax.swing.JRadioButton rbtNotas;
    private javax.swing.JRadioButton rbtTodos;
    private javax.swing.JTextField txtLocalizar;
    // End of variables declaration//GEN-END:variables

    private void selecionarTipoBusca() {
        if (rbtTodos.isSelected()) {
            lblLocalizar.setText("Texto a localizar:");
            txtLocalizar.setVisible(true);
            txtLocalizar.setEditable(false);
            txtLocalizar.setText("");
            dtcLocalizar.setVisible(false);
            dtcLocalizar.setDate(null);
        } else if (rbtNome.isSelected() || rbtEmpresa.isSelected() || rbtNotas.isSelected()) {
            lblLocalizar.setText("Texto a localizar:");
            txtLocalizar.setVisible(true);
            txtLocalizar.setEditable(true);
            txtLocalizar.setText("");
            txtLocalizar.requestFocus();
            dtcLocalizar.setVisible(false);
            dtcLocalizar.setDate(null);
        } else if (rbtNascimento.isSelected()) {
            lblLocalizar.setText("Data a localizar:");
            txtLocalizar.setVisible(false);
            txtLocalizar.setEditable(false);
            txtLocalizar.setText("");
            dtcLocalizar.setVisible(true);
            dtcLocalizar.requestFocus();
            dtcLocalizar.setDate(new Date());
        }
    }

    public JRadioButton getRbtEmpresa() {
        return rbtEmpresa;
    }

    public JRadioButton getRbtNascimento() {
        return rbtNascimento;
    }

    public JRadioButton getRbtNome() {
        return rbtNome;
    }

    public JRadioButton getRbtNotas() {
        return rbtNotas;
    }

    public JRadioButton getRbtTodos() {
        return rbtTodos;
    }

    public JTextField getTxtLocalizar() {
        return txtLocalizar;
    }

    public JDateChooser getDtcLocalizar() {
        return dtcLocalizar;
    }

    private void agruparOpcoes() {
        bgpLocalizar.add(rbtTodos);
        bgpLocalizar.add(rbtNome);
        bgpLocalizar.add(rbtEmpresa);
        bgpLocalizar.add(rbtNascimento);
        bgpLocalizar.add(rbtNotas);
    }

    private void mostrarFiltroAtual() {
        try {
            ContatoControl.mostrarFiltroAtual(this);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

}
