/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.acrs.juscadastro.view.dialog;

import com.acrs.juscadastro.control.AdvogadoControl;
import com.acrs.juscadastro.control.ContatoControl;
import com.acrs.juscadastro.view.panel.PnlAdvogado;
import com.acrs.juscadastro.view.panel.PnlContactar;
import com.acrs.juscadastro.view.panel.PnlEndereco;
import com.acrs.juscadastro.view.panel.PnlPessoal;
import com.acrs.juscadastro.view.panel.PnlTexto;
import com.acrs.juscadastro.view.interfaces.IPnlContato;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author acrs
 */
public final class DlgAgendaTelefonicaEditar extends javax.swing.JDialog implements IPnlContato {

    /**
     * Creates new form DlgAgendaEditar
     *
     * @param parent
     * @param modal
     */
    public DlgAgendaTelefonicaEditar(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Incluir Agenda");
        limpar();
        habilitar();
    }

    public DlgAgendaTelefonicaEditar(java.awt.Dialog parent, boolean modal, Integer idAgendaTelefonica) {
        super(parent, modal);
        initComponents();
        setTitle("Editar Agenda");
        limpar();
        habilitar();
        mostrarAgendaTelefonica(idAgendaTelefonica);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAgendaEditar = new javax.swing.JPanel();
        pnlPessoal = new com.acrs.juscadastro.view.panel.PnlPessoal();
        pnlEndereco = new com.acrs.juscadastro.view.panel.PnlEndereco();
        pnlContato = new com.acrs.juscadastro.view.panel.PnlContactar();
        pnlAdvogado = new com.acrs.juscadastro.view.panel.PnlAdvogado();
        pnlAdvogado.setEditavel(true);
        pnlNota = new com.acrs.juscadastro.view.panel.PnlTexto();
        btnOk = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        lblMensagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(new ImageIcon(getClass().getResource("/com/acrs/juscadastro/view/img/contatos_32x32.png")).getImage());

        pnlNota.setBorder(javax.swing.BorderFactory.createTitledBorder("Notas"));

        btnOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/acrs/juscadastro/view/img/ok_32x32.png"))); // NOI18N
        btnOk.setMnemonic('k');
        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/acrs/juscadastro/view/img/fechar_32x32.png"))); // NOI18N
        btnFechar.setMnemonic('f');
        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        lblMensagem.setFont(lblMensagem.getFont().deriveFont((lblMensagem.getFont().getStyle() & ~java.awt.Font.ITALIC) | java.awt.Font.BOLD, lblMensagem.getFont().getSize()+2));
        lblMensagem.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout pnlAgendaEditarLayout = new javax.swing.GroupLayout(pnlAgendaEditar);
        pnlAgendaEditar.setLayout(pnlAgendaEditarLayout);
        pnlAgendaEditarLayout.setHorizontalGroup(
            pnlAgendaEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAgendaEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAgendaEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlContato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlAdvogado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlNota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlPessoal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAgendaEditarLayout.createSequentialGroup()
                        .addComponent(lblMensagem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlAgendaEditarLayout.setVerticalGroup(
            pnlAgendaEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAgendaEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPessoal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlAdvogado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlNota, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAgendaEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlAgendaEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnOk)
                        .addComponent(btnFechar))
                    .addComponent(lblMensagem))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAgendaEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAgendaEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        if (validado()) {
            boolean incluir = (pnlPessoal.getIdAgendaTelefonica() == null);
            try {
                if (pnlAdvogado.getChkAdvogado().isSelected()) {
                    AdvogadoControl.gravarRegistro(this);
                } else {
                    ContatoControl.gravarRegistro(this);
                }
                // Limpar formulario se estiver em modo de inclusao ------------
                if (incluir) {
                    JOptionPane.showMessageDialog(this, "Contato incluído com sucesso");
                    limpar();
                } else {
                    this.dispose();
                }
                // Foco para a primeira caixa de texto -------------------------
                pnlPessoal.getTxtNome().requestFocus();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (UnsupportedLookAndFeelException | ClassNotFoundException | InstantiationException | IllegalAccessException e) {
        }

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgAgendaTelefonicaEditar dialog = new DlgAgendaTelefonicaEditar(new javax.swing.JDialog(), true, 101);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel lblMensagem;
    private com.acrs.juscadastro.view.panel.PnlAdvogado pnlAdvogado;
    private javax.swing.JPanel pnlAgendaEditar;
    private com.acrs.juscadastro.view.panel.PnlContactar pnlContato;
    private com.acrs.juscadastro.view.panel.PnlEndereco pnlEndereco;
    private com.acrs.juscadastro.view.panel.PnlTexto pnlNota;
    private com.acrs.juscadastro.view.panel.PnlPessoal pnlPessoal;
    // End of variables declaration//GEN-END:variables

    // Busca de Componentes ----------------------------------------------------
    public PnlContactar getPnlContactar() {
        return pnlContato;
    }

    public PnlEndereco getPnlEndereco() {
        return pnlEndereco;
    }

    public PnlTexto getPnlNota() {
        return pnlNota;
    }

    public PnlPessoal getPnlPessoal() {
        return pnlPessoal;
    }

    public PnlAdvogado getPnlAdvogado() {
        return pnlAdvogado;
    }

    // Funcoes de Controle -----------------------------------------------------
    public void limpar() {
        pnlPessoal.limpar();
        pnlEndereco.limpar();
        pnlContato.limpar();
        pnlAdvogado.limpar();
        pnlNota.limpar();
    }

    private void habilitar() {
        pnlPessoal.habilitar();
        pnlEndereco.habilitar();
        pnlContato.habilitar();
        pnlAdvogado.habilitar();
        pnlNota.habilitar();
    }

    private boolean validado() {

        lblMensagem.setText(pnlPessoal.validarPreenchimentoNome());
        if (!lblMensagem.getText().equals("")) {
            return false;
        }

        lblMensagem.setText(pnlPessoal.validarUnicidadeNome());
        if (!lblMensagem.getText().equals("")) {
            return false;
        }

        lblMensagem.setText(pnlPessoal.validarPreenchimentoCPFJ());
        if (!lblMensagem.getText().equals("")) {
            return false;
        }

        lblMensagem.setText(pnlPessoal.validarUnicidadeCPFJ());
        if (!lblMensagem.getText().equals("")) {
            return false;
        }

        lblMensagem.setText(pnlPessoal.validarFormatoNascimento());
        if (!lblMensagem.getText().equals("")) {
            return false;
        }

        lblMensagem.setText(pnlAdvogado.validarPreenchimentoOAB());
        return lblMensagem.getText().equals("");
    }

    // Acesso a camada de controle ---------------------------------------------
    private void mostrarAgendaTelefonica(Integer id) {
        pnlPessoal.setIdAgendaTelefonica(id);
        try {
            ContatoControl.mostrarRegistro(this);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            dispose();
        }
    }
}
