/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.acrs.juscadastro.view.dialog;

import com.acrs.juscadastro.control.AdvogadoControl;
import com.acrs.juscadastro.control.ContatoControl;
import com.acrs.juscadastro.control.ProcessoControl;
import com.acrs.juscadastro.view.panel.PnlEndereco;
import com.acrs.juscadastro.view.panel.PnlNome;
import com.acrs.juscadastro.view.panel.PnlProcesso;
import com.acrs.juscadastro.view.panel.PnlTexto;
import com.acrs.juscadastro.view.interfaces.IPnlProcesso;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author acrs
 */
public final class DlgProcessoEditar extends javax.swing.JDialog implements IPnlProcesso {

    /**
     * Creates new form DlgAgendaEditar
     *
     * @param parent
     * @param modal
     */
    public DlgProcessoEditar(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Incluir Processo");
        limpar();
        habilitar();
    }

    public DlgProcessoEditar(java.awt.Dialog parent, boolean modal, Integer idProcesso) {
        super(parent, modal);
        initComponents();
        setTitle("Editar Processo");
        limpar();
        habilitar();
        mostrarProcesso(idProcesso);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAgendaEditar = new javax.swing.JPanel();
        btnOk = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        lblMensagem = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        pnlTabProcesso1 = new javax.swing.JPanel();
        pnlAndamento = new com.acrs.juscadastro.view.panel.PnlTexto();
        pnlProcesso1 = new com.acrs.juscadastro.view.panel.PnlProcesso();
        pnlEndereco1 = new com.acrs.juscadastro.view.panel.PnlEndereco();
        pnlTabContato = new javax.swing.JPanel();
        pnlCliente = new com.acrs.juscadastro.view.panel.PnlNome();
        pnlAdvogado = new com.acrs.juscadastro.view.panel.PnlNome();
        pnlTestemunha = new com.acrs.juscadastro.view.panel.PnlNome();
        pnlParteContraria = new com.acrs.juscadastro.view.panel.PnlNome();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(new ImageIcon(getClass().getResource("/com/acrs/juscadastro/view/img/contatos_32x32.png")).getImage());

        btnOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/acrs/juscadastro/view/img/ok_32x32.png"))); // NOI18N
        btnOk.setMnemonic('k');
        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/acrs/juscadastro/view/img/fechar_32x32.png"))); // NOI18N
        btnFechar.setMnemonic('f');
        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        lblMensagem.setFont(lblMensagem.getFont().deriveFont((lblMensagem.getFont().getStyle() & ~java.awt.Font.ITALIC) | java.awt.Font.BOLD, lblMensagem.getFont().getSize()+2));
        lblMensagem.setForeground(new java.awt.Color(255, 0, 0));

        pnlAndamento.setBorder(javax.swing.BorderFactory.createTitledBorder("Andamento"));

        javax.swing.GroupLayout pnlTabProcesso1Layout = new javax.swing.GroupLayout(pnlTabProcesso1);
        pnlTabProcesso1.setLayout(pnlTabProcesso1Layout);
        pnlTabProcesso1Layout.setHorizontalGroup(
            pnlTabProcesso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabProcesso1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTabProcesso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlProcesso1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlAndamento, javax.swing.GroupLayout.DEFAULT_SIZE, 816, Short.MAX_VALUE)
                    .addComponent(pnlEndereco1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlTabProcesso1Layout.setVerticalGroup(
            pnlTabProcesso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabProcesso1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlProcesso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlEndereco1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlAndamento, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Processo", pnlTabProcesso1);

        pnlCliente.setBorder(javax.swing.BorderFactory.createTitledBorder("Clientes"));

        pnlAdvogado.setBorder(javax.swing.BorderFactory.createTitledBorder("Advogados"));

        pnlTestemunha.setBorder(javax.swing.BorderFactory.createTitledBorder("Testemunhas"));

        pnlParteContraria.setBorder(javax.swing.BorderFactory.createTitledBorder("Partes Contrárias"));

        javax.swing.GroupLayout pnlTabContatoLayout = new javax.swing.GroupLayout(pnlTabContato);
        pnlTabContato.setLayout(pnlTabContatoLayout);
        pnlTabContatoLayout.setHorizontalGroup(
            pnlTabContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabContatoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTabContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 816, Short.MAX_VALUE)
                    .addComponent(pnlAdvogado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTestemunha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlParteContraria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlTabContatoLayout.setVerticalGroup(
            pnlTabContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabContatoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlAdvogado, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTestemunha, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlParteContraria, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Contatos", pnlTabContato);

        javax.swing.GroupLayout pnlAgendaEditarLayout = new javax.swing.GroupLayout(pnlAgendaEditar);
        pnlAgendaEditar.setLayout(pnlAgendaEditarLayout);
        pnlAgendaEditarLayout.setHorizontalGroup(
            pnlAgendaEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAgendaEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAgendaEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAgendaEditarLayout.createSequentialGroup()
                        .addComponent(lblMensagem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTabbedPane2))
                .addContainerGap())
        );
        pnlAgendaEditarLayout.setVerticalGroup(
            pnlAgendaEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAgendaEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addGap(31, 31, 31)
                .addGroup(pnlAgendaEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlAgendaEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnOk)
                        .addComponent(btnFechar))
                    .addComponent(lblMensagem))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAgendaEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAgendaEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        /*if (validado()) {
            boolean incluir = (pnlProcesso.getIdProcesso() == null);
            try {
                ProcessoControl.gravarRegistro(this);
                // Limpar formulario se estiver em modo de inclusao ------------
                if (incluir) {
                    JOptionPane.showMessageDialog(this, "Processo incluído com sucesso");
                    limpar();
                } else {
                    this.dispose();
                }
                // Foco para a primeira caixa de texto -------------------------
                pnlProcesso.getTxtComarca().requestFocus();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }*/
    }//GEN-LAST:event_btnOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (UnsupportedLookAndFeelException | ClassNotFoundException | InstantiationException | IllegalAccessException e) {
        }

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgProcessoEditar dialog = new DlgProcessoEditar(new javax.swing.JDialog(), true, 101);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnOk;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lblMensagem;
    private com.acrs.juscadastro.view.panel.PnlNome pnlAdvogado;
    private javax.swing.JPanel pnlAgendaEditar;
    private com.acrs.juscadastro.view.panel.PnlTexto pnlAndamento;
    private com.acrs.juscadastro.view.panel.PnlNome pnlCliente;
    private com.acrs.juscadastro.view.panel.PnlEndereco pnlEndereco1;
    private com.acrs.juscadastro.view.panel.PnlNome pnlParteContraria;
    private com.acrs.juscadastro.view.panel.PnlProcesso pnlProcesso1;
    private javax.swing.JPanel pnlTabContato;
    private javax.swing.JPanel pnlTabProcesso1;
    private com.acrs.juscadastro.view.panel.PnlNome pnlTestemunha;
    // End of variables declaration//GEN-END:variables

    // Busca de Componentes ----------------------------------------------------
    /*public PnlProcesso getPnlProcesso() {
        return pnlProcesso;
    }*/

    /*public PnlEndereco getPnlEndereco() {
        return pnlEndereco;
    }*/

    public PnlTexto getPnlAndamento() {
        return pnlAndamento;
    }

    public PnlNome getPnlCliente() {
        return pnlCliente;
    }

    public PnlNome getPnlAdvogado() {
        return pnlAdvogado;
    }

    // Funcoes de Controle -----------------------------------------------------
    public void limpar() {
/*        pnlPessoal.limpar();
        pnlEndereco.limpar();
        pnlContato.limpar();
        pnlAdvogado.limpar();
        pnlNota.limpar();*/
    }

    private void habilitar() {
        /*pnlPessoal.habilitar();
        pnlEndereco.habilitar();
        pnlContato.habilitar();
        pnlAdvogado.habilitar();
        pnlNota.habilitar();*/
    }

    private boolean validado() {

      /*  lblMensagem.setText(pnlPessoal.validarPreenchimentoNome());
        if (!lblMensagem.getText().equals("")) {
            return false;
        }

        lblMensagem.setText(pnlPessoal.validarUnicidadeNome());
        if (!lblMensagem.getText().equals("")) {
            return false;
        }

        lblMensagem.setText(pnlPessoal.validarPreenchimentoCPFJ());
        if (!lblMensagem.getText().equals("")) {
            return false;
        }

        lblMensagem.setText(pnlPessoal.validarUnicidadeCPFJ());
        if (!lblMensagem.getText().equals("")) {
            return false;
        }

        lblMensagem.setText(pnlPessoal.validarFormatoNascimento());
        if (!lblMensagem.getText().equals("")) {
            return false;
        }

        lblMensagem.setText(pnlAdvogado.validarPreenchimentoOAB());
        return lblMensagem.getText().equals("");*/
        return false;
    }

    // Acesso a camada de controle ---------------------------------------------
    private void mostrarProcesso(Integer id) {
       /* pnlPessoal.setIdAgendaTelefonica(id);
        try {
            ProcessoControl.mostrarRegistro(this);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            dispose();
        }*/
    }
}
