/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.acrs.juscadastro.view;

import com.acrs.juscadastro.control.ContatoControl;
import com.acrs.juscadastro.util.ForcedListSelectionModel;
import javax.swing.ImageIcon;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author allan
 */
public class DlgContatoTabela extends javax.swing.JDialog {

    /**
     * Creates new form DlgAgendaTabela
     * @param parent
     * @param modal
     */
    public DlgContatoTabela(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ContatoControl.listarRegistros(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAgenda = new javax.swing.JPanel();
        sclAgenda = new javax.swing.JScrollPane();
        tblAgenda = new javax.swing.JTable();
        lblMensagem01 = new javax.swing.JLabel();
        lblMensagem02 = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Contatos cadastrados");
        setIconImage(new ImageIcon(getClass().getResource("/com/acrs/juscadastro/view/img/contatos_32x32.png")).getImage());

        pnlAgenda.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        sclAgenda.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        tblAgenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Allan Carlos do Rosário Souza", "10047953780", "17/08/1982", "Mktec Marketing de Relacionamento", "Analista de Marketing", "Avenida Marechal Fonteneli", "4311", "Rua 6 Casa 171", "21750-000", "Jardim Sulacap", "Rio de Janeiro", "RJ", "21", "35465478", "21", "969712222", "21", "35465478", "allan.carloss@gmail.com", "7777778899"},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "CPF/CNPJ", "Nascimento", "Empresa", "Cargo", "Logradouro", "Nº", "Complemento", "CEP", "Bairro", "Cidade", "UF", "DDD Fixo", "Tel. Fixo", "DDD Móvel", "Tel. Móvel", "DDD Fax", "Tel. Fax", "E-mail", "Oab"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAgenda.setSelectionModel(new ForcedListSelectionModel());
        tblAgenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAgendaMouseClicked(evt);
            }
        });
        sclAgenda.setViewportView(tblAgenda);
        if (tblAgenda.getColumnModel().getColumnCount() > 0) {
            tblAgenda.getColumnModel().getColumn(0).setPreferredWidth(200);
            tblAgenda.getColumnModel().getColumn(1).setPreferredWidth(75);
            tblAgenda.getColumnModel().getColumn(2).setPreferredWidth(50);
            tblAgenda.getColumnModel().getColumn(3).setPreferredWidth(160);
            tblAgenda.getColumnModel().getColumn(4).setPreferredWidth(100);
            tblAgenda.getColumnModel().getColumn(5).setPreferredWidth(100);
            tblAgenda.getColumnModel().getColumn(6).setPreferredWidth(30);
            tblAgenda.getColumnModel().getColumn(11).setPreferredWidth(15);
            tblAgenda.getColumnModel().getColumn(12).setPreferredWidth(20);
            tblAgenda.getColumnModel().getColumn(13).setPreferredWidth(50);
            tblAgenda.getColumnModel().getColumn(14).setPreferredWidth(20);
            tblAgenda.getColumnModel().getColumn(15).setPreferredWidth(50);
            tblAgenda.getColumnModel().getColumn(16).setPreferredWidth(20);
            tblAgenda.getColumnModel().getColumn(17).setPreferredWidth(50);
            tblAgenda.getColumnModel().getColumn(19).setPreferredWidth(50);
        }

        lblMensagem01.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblMensagem01.setText("O item selecionado será apresentado.");

        lblMensagem02.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblMensagem02.setText("Clique sobre o item desejado.");

        btnOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/acrs/juscadastro/view/img/ok_32x32.png"))); // NOI18N
        btnOk.setMnemonic('k');
        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAgendaLayout = new javax.swing.GroupLayout(pnlAgenda);
        pnlAgenda.setLayout(pnlAgendaLayout);
        pnlAgendaLayout.setHorizontalGroup(
            pnlAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAgendaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sclAgenda, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
                    .addGroup(pnlAgendaLayout.createSequentialGroup()
                        .addGroup(pnlAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMensagem02)
                            .addComponent(lblMensagem01))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOk)))
                .addContainerGap())
        );
        pnlAgendaLayout.setVerticalGroup(
            pnlAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAgendaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sclAgenda, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAgendaLayout.createSequentialGroup()
                        .addComponent(lblMensagem02)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblMensagem01))
                    .addComponent(btnOk, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAgenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAgenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        if (tblAgenda.getSelectedRow()>-1){
            ContatoControl.irParaRegistro(tblAgenda.getSelectedRow());
            this.dispose();
        } else {
            this.dispose();
        }
    }//GEN-LAST:event_btnOkActionPerformed

    private void tblAgendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAgendaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblAgendaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (UnsupportedLookAndFeelException | ClassNotFoundException | InstantiationException | IllegalAccessException e) {
        }

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgContatoTabela dialog = new DlgContatoTabela(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public JTable getTblAgenda() {
        return tblAgenda;
    }

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel lblMensagem01;
    private javax.swing.JLabel lblMensagem02;
    private javax.swing.JPanel pnlAgenda;
    private javax.swing.JScrollPane sclAgenda;
    private javax.swing.JTable tblAgenda;
    // End of variables declaration//GEN-END:variables

    
}
