/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.acrs.juscadastro.view;

import com.acrs.juscadastro.view.dialog.DlgProcesso;
import com.acrs.juscadastro.view.dialog.DlgAgendaTelefonica;
import com.acrs.juscadastro.view.dialog.DlgSobre;
import com.acrs.juscadastro.util.Timer;
import javax.swing.ImageIcon;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author allan
 */
public class FrmJusCadastro extends javax.swing.JFrame {

    /**
     * Creates new form AcompanhamentoDeProcessos
     */
    public FrmJusCadastro() {
        initComponents();
        mostrarDataHoraAtual();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        tlbarPrincipal = new javax.swing.JToolBar();
        btnAcompanhamentoDeProcessos = new javax.swing.JButton();
        btnAgendaTelefonica = new javax.swing.JButton();
        separadorBFerramentas = new javax.swing.JToolBar.Separator();
        btnAgendaDeCompromissos = new javax.swing.JButton();
        btnCompromissosDoDia = new javax.swing.JButton();
        lblAplicativo = new javax.swing.JLabel();
        lblVersao = new javax.swing.JLabel();
        lblFuncao = new javax.swing.JLabel();
        lblDataHora = new javax.swing.JLabel();
        pnlLogo = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        mnubarPrincipal = new javax.swing.JMenuBar();
        mnuGeral = new javax.swing.JMenu();
        btnSaida = new javax.swing.JMenuItem();
        mnuUtilitarios = new javax.swing.JMenu();
        mnuiAcompanhamentoDeProcessos = new javax.swing.JMenuItem();
        mnuiAgendaTelefonica = new javax.swing.JMenuItem();
        separadorMnuUtilitarios = new javax.swing.JPopupMenu.Separator();
        mnuiAgendaDeCompromissos = new javax.swing.JMenuItem();
        mnuiCompromissosDoDia = new javax.swing.JMenuItem();
        mnuAjuda = new javax.swing.JMenu();
        mnuiSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JusCadastro - Acompanhamento de Processos");
        setExtendedState(MAXIMIZED_BOTH);
        setIconImage(new ImageIcon(getClass().getResource("/com/acrs/juscadastro/view/img/logo_32x32.png")).getImage());
        setPreferredSize(new java.awt.Dimension(700, 700));

        pnlPrincipal.setBackground(new java.awt.Color(192, 192, 192));

        tlbarPrincipal.setFloatable(false);
        tlbarPrincipal.setRollover(true);

        btnAcompanhamentoDeProcessos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/acrs/juscadastro/view/img/processo_48x48.png"))); // NOI18N
        btnAcompanhamentoDeProcessos.setToolTipText("Acompanhamento de Processos");
        btnAcompanhamentoDeProcessos.setFocusable(false);
        btnAcompanhamentoDeProcessos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAcompanhamentoDeProcessos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAcompanhamentoDeProcessos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcompanhamentoDeProcessosActionPerformed(evt);
            }
        });
        tlbarPrincipal.add(btnAcompanhamentoDeProcessos);

        btnAgendaTelefonica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/acrs/juscadastro/view/img/contatos_48x48.png"))); // NOI18N
        btnAgendaTelefonica.setToolTipText("Contatos");
        btnAgendaTelefonica.setFocusable(false);
        btnAgendaTelefonica.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgendaTelefonica.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAgendaTelefonica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendaTelefonicaActionPerformed(evt);
            }
        });
        tlbarPrincipal.add(btnAgendaTelefonica);
        tlbarPrincipal.add(separadorBFerramentas);

        btnAgendaDeCompromissos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/acrs/juscadastro/view/img/compromisso_48x48.png"))); // NOI18N
        btnAgendaDeCompromissos.setToolTipText("Agenda de Compromissos");
        btnAgendaDeCompromissos.setFocusable(false);
        btnAgendaDeCompromissos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgendaDeCompromissos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlbarPrincipal.add(btnAgendaDeCompromissos);

        btnCompromissosDoDia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/acrs/juscadastro/view/img/dia_48x48.png"))); // NOI18N
        btnCompromissosDoDia.setToolTipText("Compromissos do Dia");
        btnCompromissosDoDia.setFocusable(false);
        btnCompromissosDoDia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCompromissosDoDia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlbarPrincipal.add(btnCompromissosDoDia);

        lblAplicativo.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        lblAplicativo.setForeground(new java.awt.Color(0, 0, 102));
        lblAplicativo.setText("JusCadastro");

        lblVersao.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        lblVersao.setForeground(new java.awt.Color(0, 0, 102));
        lblVersao.setText("v. 1.0");

        lblFuncao.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        lblFuncao.setForeground(new java.awt.Color(153, 51, 51));
        lblFuncao.setText("Gerenciador de Escritório");

        lblDataHora.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDataHora.setText("01/01/2014 00:00:00");

        pnlLogo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/acrs/juscadastro/view/img/logo_sobre_51x50.png"))); // NOI18N

        javax.swing.GroupLayout pnlLogoLayout = new javax.swing.GroupLayout(pnlLogo);
        pnlLogo.setLayout(pnlLogoLayout);
        pnlLogoLayout.setHorizontalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLogo)
        );
        pnlLogoLayout.setVerticalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLogoLayout.createSequentialGroup()
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tlbarPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDataHora)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addComponent(lblAplicativo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblVersao))
                    .addComponent(lblFuncao))
                .addGap(14, 14, 14))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addComponent(tlbarPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 487, Short.MAX_VALUE)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblVersao)
                            .addComponent(lblAplicativo))
                        .addGap(8, 8, 8)
                        .addComponent(lblFuncao))
                    .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(pnlLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblDataHora)))
                .addContainerGap())
        );

        mnuGeral.setText("Geral");

        btnSaida.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        btnSaida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/acrs/juscadastro/view/img/sair_32x32.png"))); // NOI18N
        btnSaida.setText("Saída");
        btnSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaidaActionPerformed(evt);
            }
        });
        mnuGeral.add(btnSaida);

        mnubarPrincipal.add(mnuGeral);

        mnuUtilitarios.setText("Utilitários");

        mnuiAcompanhamentoDeProcessos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuiAcompanhamentoDeProcessos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/acrs/juscadastro/view/img/processo_32x32.png"))); // NOI18N
        mnuiAcompanhamentoDeProcessos.setText("Acompanhamento de Processos");
        mnuiAcompanhamentoDeProcessos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiAcompanhamentoDeProcessosActionPerformed(evt);
            }
        });
        mnuUtilitarios.add(mnuiAcompanhamentoDeProcessos);

        mnuiAgendaTelefonica.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuiAgendaTelefonica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/acrs/juscadastro/view/img/contatos_32x32.png"))); // NOI18N
        mnuiAgendaTelefonica.setText("Agenda Telefônica");
        mnuiAgendaTelefonica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiAgendaTelefonicaActionPerformed(evt);
            }
        });
        mnuUtilitarios.add(mnuiAgendaTelefonica);
        mnuUtilitarios.add(separadorMnuUtilitarios);

        mnuiAgendaDeCompromissos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuiAgendaDeCompromissos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/acrs/juscadastro/view/img/compromisso_32x32.png"))); // NOI18N
        mnuiAgendaDeCompromissos.setText("Agenda de Compromissos");
        mnuUtilitarios.add(mnuiAgendaDeCompromissos);

        mnuiCompromissosDoDia.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuiCompromissosDoDia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/acrs/juscadastro/view/img/dia_32x32.png"))); // NOI18N
        mnuiCompromissosDoDia.setText("Compromissos do Dia");
        mnuUtilitarios.add(mnuiCompromissosDoDia);

        mnubarPrincipal.add(mnuUtilitarios);

        mnuAjuda.setText("Ajuda");

        mnuiSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuiSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/acrs/juscadastro/view/img/sobre_32x32.png"))); // NOI18N
        mnuiSobre.setText("Sobre...");
        mnuiSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiSobreActionPerformed(evt);
            }
        });
        mnuAjuda.add(mnuiSobre);

        mnubarPrincipal.add(mnuAjuda);

        setJMenuBar(mnubarPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaidaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSaidaActionPerformed

    private void mnuiAgendaTelefonicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiAgendaTelefonicaActionPerformed
        new DlgAgendaTelefonica(this, true).setVisible(true);
    }//GEN-LAST:event_mnuiAgendaTelefonicaActionPerformed

    private void btnAcompanhamentoDeProcessosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcompanhamentoDeProcessosActionPerformed
        mnuiAcompanhamentoDeProcessos.doClick();
    }//GEN-LAST:event_btnAcompanhamentoDeProcessosActionPerformed

    private void mnuiAcompanhamentoDeProcessosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiAcompanhamentoDeProcessosActionPerformed
        new DlgProcesso(this, true).setVisible(true);
    }//GEN-LAST:event_mnuiAcompanhamentoDeProcessosActionPerformed

    private void btnAgendaTelefonicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendaTelefonicaActionPerformed
        mnuiAgendaTelefonica.doClick();
    }//GEN-LAST:event_btnAgendaTelefonicaActionPerformed

    private void mnuiSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiSobreActionPerformed
        new DlgSobre(this, true).setVisible(true);
    }//GEN-LAST:event_mnuiSobreActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcompanhamentoDeProcessos;
    private javax.swing.JButton btnAgendaDeCompromissos;
    private javax.swing.JButton btnAgendaTelefonica;
    private javax.swing.JButton btnCompromissosDoDia;
    private javax.swing.JMenuItem btnSaida;
    private javax.swing.JLabel lblAplicativo;
    private javax.swing.JLabel lblDataHora;
    private javax.swing.JLabel lblFuncao;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblVersao;
    private javax.swing.JMenu mnuAjuda;
    private javax.swing.JMenu mnuGeral;
    private javax.swing.JMenu mnuUtilitarios;
    private javax.swing.JMenuBar mnubarPrincipal;
    private javax.swing.JMenuItem mnuiAcompanhamentoDeProcessos;
    private javax.swing.JMenuItem mnuiAgendaDeCompromissos;
    private javax.swing.JMenuItem mnuiAgendaTelefonica;
    private javax.swing.JMenuItem mnuiCompromissosDoDia;
    private javax.swing.JMenuItem mnuiSobre;
    private javax.swing.JPanel pnlLogo;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JToolBar.Separator separadorBFerramentas;
    private javax.swing.JPopupMenu.Separator separadorMnuUtilitarios;
    private javax.swing.JToolBar tlbarPrincipal;
    // End of variables declaration//GEN-END:variables

    public static void main(String[] args) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (UnsupportedLookAndFeelException | ClassNotFoundException | InstantiationException | IllegalAccessException e) {
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FrmJusCadastro().setVisible(true);
            }
        });
    }

    private void mostrarDataHoraAtual() {
        Timer timer = new Timer();
        timer.start();
        timer.label = lblDataHora;
    }
}
